### ISSUE TITLE
Gem compatibility with Zilliz Cloud / Hosted providers

### ISSUE THREAD

**Issue by wTheRockb** [andreibondarev/milvus#2]
Have you been able to get this working on Zilliz cloud?

When running a `search`, I get a status code [464 ](https://http.dev/464) on the Faraday post. 

I'm building the client as
```
client = Milvus::Client.new(
        url: 'https://[my user]:[my password]@in01-e33b496aaa85ceb.aws-us-west-2.vectordb.zillizcloud.com:19531'
)
```

Is that the correct way to pass the authentication to the client?

**Comment by andreibondarev** [comment]
@wTheRockb It is the correct way to pass the authentication but, unfortunately, Zilliz Cloud does not support the REST API yet which is on port 9091. I had developed and tested this gem only against Milvus running on localhost.

**Comment by wTheRockb** [comment]
Ah got it, thanks for the quick response. I found the library from your tweet so I figured there was a chance.

**Comment by andreibondarev** [comment]
Please do bug @zilliztech about this. REST API feels like a must have for managed cloud vector DB offering.
